In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# 데이터분석 4종 세트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

base_path = "/content/drive/MyDrive/Colab Notebooks/platform_subscribe/"

train = pd.read_csv(base_path + "train.csv")
test = pd.read_csv(base_path + "test.csv")
submission = pd.read_csv(base_path + "sample_submission.csv")

In [3]:
# 1. Linear Classifier
from sklearn.linear_model import SGDClassifier
# 2. Logistic Regression
from sklearn.linear_model import LogisticRegression
# 3. Decision Tree
from sklearn.tree import DecisionTreeClassifier
# 4. Random Forest
from sklearn.ensemble import RandomForestClassifier


# 평가 지표
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

evulation_metric = f1_score

### 1. 'average_time_per_learning_session','average_login_time' + Random Forest


In [6]:
X=train[['average_time_per_learning_session','average_login_time']]
y=train.target

In [7]:
from sklearn.model_selection import train_test_split
# 트테트테
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train,y_train, test_size=0.25, random_state=42)

# 6:2:2 = train: validation:test
print(X_train.shape, X_val.shape, X_test.shape, y_train.shape, y_val.shape, y_test.shape)

(6000, 2) (2000, 2) (2000, 2) (6000,) (2000,) (2000,)


In [10]:
clf_dt = DecisionTreeClassifier()
clf_rf = RandomForestClassifier()

clf_dt.fit(X_train,y_train)
clf_rf.fit(X_train,y_train)

pred_val_dt=clf_dt.predict(X_val)
pred_val_rf=clf_rf.predict(X_val)

print('Desicion Tree : ' , evulation_metric(y_val, pred_val_dt))
print(pred_val_dt)
print('Random Forest : ' , evulation_metric(y_val, pred_val_rf))
print(pred_val_rf)

Desicion Tree :  0.6229376257545272
[0 1 1 ... 0 1 0]
Random Forest :  0.668417104276069
[0 1 1 ... 1 1 1]


#### X_test 확인

In [11]:
pred_test_dt=clf_dt.predict(X_test)
pred_test_rf=clf_rf.predict(X_test)

print('Desicion Tree : ' , evulation_metric(y_test, pred_test_dt))
print(pred_test_dt)
print('Random Forest : ' , evulation_metric(y_test, pred_test_rf))
print(pred_test_rf)

Desicion Tree :  0.6169354838709679
[1 1 1 ... 0 1 1]
Random Forest :  0.6621621621621622
[0 1 1 ... 1 0 1]


#### submission

In [13]:
X_submission=test[['average_time_per_learning_session','average_login_time']]
print(X_submission)
preds=clf_rf.predict(X_submission)
preds

      average_time_per_learning_session  average_login_time
0                              7.047243           11.173051
1                             24.583327           13.448592
2                              1.707616           18.548201
3                             21.391389           13.383311
4                             18.126987           11.919663
...                                 ...                 ...
9995                          90.251023           11.924481
9996                          10.205804           12.395364
9997                          20.346781           17.036811
9998                         156.521711           15.758179
9999                          53.633453           19.618550

[10000 rows x 2 columns]


array([0, 1, 1, ..., 0, 0, 0])

In [15]:
submission['target']=preds
submission

user_id  target
0     0001d6e9       0
1     0002c77d       1
2     0002df5b       1
3     000b6068       1
4     00184a0c       1
...        ...     ...
9995  ffe2eba5       1
9996  ffe710f1       1
9997  ffeccdef       0
9998  fff3fcea       0
9999  fff4b04b       0

[10000 rows x 2 columns]

In [16]:
submission.to_csv(base_path+"submission_1209_1.csv", index=False)