In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# 데이터분석 4종 세트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

base_path = "/content/drive/MyDrive/Colab Notebooks/platform_subscribe/"

train = pd.read_csv(base_path + "train.csv")
test = pd.read_csv(base_path + "test.csv")
submission = pd.read_csv(base_path + "sample_submission.csv")

# 1. EDA

- user_id	사용자의 고유 식별자
- subscription_duration	사용자가 서비스에 가입한 기간 (월)
- recent_login_time	사용자가 마지막으로 로그인한 시간 (일)
- average_login_time	사용자의 일반적인 로그인 시간
- average_time_per_learning_session	각 학습 세션에 소요된 평균 시간 (분)
- monthly_active_learning_days	월간 활동적인 학습 일수
- total_completed_courses	완료한 총 코스 수
- recent_learning_achievement	최근 학습 성취도
- abandoned_learning_sessions	중단된 학습 세션 수
- community_engagement_level	커뮤니티 참여도
- preferred_difficulty_level	선호하는 난이도
- subscription_type	구독 유형
- customer_inquiry_history	고객 문의 이력
- payment_pattern	"
    사용자의 지난 3개월 간의 결제 패턴을 10진수로 표현한 값.
    - 7: 3개월 모두 결제함
    - 6: 첫 2개월은 결제했으나 마지막 달에는 결제하지 않음
    - 5: 첫 달과 마지막 달에 결제함
    - 4: 첫 달에만 결제함
    - 3: 마지막 2개월에 결제함
    - 2: 가운데 달에만 결제함
    - 1: 마지막 달에만 결제함
    - 0: 3개월 동안 결제하지 않음
    "
- target	사용자가 다음 달에도 구독을 계속할지 (1) 또는 취소할지 (0)를 나타냅니다.

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   user_id                            10000 non-null  object 
 1   subscription_duration              10000 non-null  int64  
 2   recent_login_time                  10000 non-null  int64  
 3   average_login_time                 10000 non-null  float64
 4   average_time_per_learning_session  10000 non-null  float64
 5   monthly_active_learning_days       10000 non-null  int64  
 6   total_completed_courses            10000 non-null  int64  
 7   recent_learning_achievement        10000 non-null  float64
 8   abandoned_learning_sessions        10000 non-null  int64  
 9   community_engagement_level         10000 non-null  int64  
 10  preferred_difficulty_level         10000 non-null  object 
 11  subscription_type                  10000 non-null  obje

In [5]:
train_ONE = pd.get_dummies(train, columns=['preferred_difficulty_level', 'subscription_type'])
train_ONE

user_id  subscription_duration  recent_login_time  average_login_time  \
0     b919c29d                     13                 14           14.946163   
1     a0a60abb                     16                 18           18.453224   
2     b9f171ae                     22                  1           16.195228   
3     5dc0ba8b                      1                 19           17.628656   
4     65c83654                      4                  5           21.390656   
...        ...                    ...                ...                 ...   
9995  ae6b76bc                     22                 29           14.727623   
9996  24588752                     10                 11           19.374054   
9997  e4622a54                      7                 27           18.240978   
9998  e07fbad9                     11                  7           18.783800   
9999  e12dcb55                     10                  5           13.073230   

      average_time_per_learning_session  monthly_active_learning_days  \
0                              8.427187                            18   
1                             72.646087                            16   
2                             21.774492                            13   
3                             42.659066                            19   
4                             30.744287                            19   
...                                 ...                           ...   
9995                          84.053558                            18   
9996                          45.464833                             9   
9997                         127.302411                            24   
9998                           5.297234                            10   
9999                          28.120031                             3   

      total_completed_courses  recent_learning_achievement  \
0                          16                    68.360455   
1                          13                    97.567322   
2                          14                    94.358763   
3                          18                    70.153228   
4                          10                    81.917908   
...                       ...                          ...   
9995                       16                    64.966803   
9996                        8                    82.750244   
9997                       14                    81.567839   
9998                       10                    89.885656   
9999                       13                    64.811297   

      abandoned_learning_sessions  community_engagement_level  \
0                               3                           4   
1                               2                           3   
2                               3                           4   
3                               0                           3   
4                               2                           4   
...                           ...                         ...   
9995                            2                           5   
9996                            3                           3   
9997                            3                           5   
9998                            4                           5   
9999                            4                           5   

      customer_inquiry_history  payment_pattern  target  \
0                            4                5       0   
1                            1                6       1   
2                            0                7       1   
3                            1                0       1   
4                            3                0       1   
...                        ...              ...     ...   
9995                         1                1       1   
9996                         2                7       1   
9997                         1                6       1   
9998                         2                0      

# 2. ML

In [6]:
# 1. Linear Classifier
from sklearn.linear_model import SGDClassifier
# 2. Logistic Regression
from sklearn.linear_model import LogisticRegression
# 3. Decision Tree
from sklearn.tree import DecisionTreeClassifier
# 4. Random Forest
from sklearn.ensemble import RandomForestClassifier


# 평가 지표
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

evulation_metric = f1_score

# 3. overfitting 해결

## 1. feature 개수 줄이기



In [7]:
X=train_ONE[['average_time_per_learning_session','average_login_time','recent_learning_achievement','recent_login_time']]
y=train_ONE.target
X

average_time_per_learning_session  average_login_time  \
0                              8.427187           14.946163   
1                             72.646087           18.453224   
2                             21.774492           16.195228   
3                             42.659066           17.628656   
4                             30.744287           21.390656   
...                                 ...                 ...   
9995                          84.053558           14.727623   
9996                          45.464833           19.374054   
9997                         127.302411           18.240978   
9998                           5.297234           18.783800   
9999                          28.120031           13.073230   

      recent_learning_achievement  recent_login_time  
0                       68.360455                 14  
1                       97.567322                 18  
2                       94.358763                  1  
3                       70.153228                 19  
4                       81.917908                  5  
...                           ...                ...  
9995                    64.966803                 29  
9996                    82.750244                 11  
9997                    81.567839                 27  
9998                    89.885656                  7  
9999                    64.811297                  5  

[10000 rows x 4 columns]

In [8]:
from sklearn.model_selection import train_test_split
# 트테트테
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train,y_train, test_size=0.25, random_state=42)

# 6:2:2 = train: validation:test
print(X_train.shape, X_val.shape, X_test.shape, y_train.shape, y_val.shape, y_test.shape)

(6000, 4) (2000, 4) (2000, 4) (6000,) (2000,) (2000,)


## 2. data-scaling

In [9]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
std.fit(X_train)
X_train_scaled = std.transform(X_train)
X_val_scaled = std.transform(X_val)
X_train_scaled

array([[-0.59958708,  0.80864548, -0.6357813 ,  1.07770741],
       [ 1.07284724, -0.36723002, -1.40754599, -0.83903327],
       [-0.92446115,  0.65026148, -0.35083719, -0.59944068],
       ...,
       [-0.43392141,  1.69947247, -0.41209445, -0.3598481 ],
       [ 0.25508129, -0.34222967,  0.62728622, -1.67760732],
       [-0.21772338, -2.11150726,  0.82332236,  0.71831854]])

In [10]:
model = RandomForestClassifier()
model.fit(X_train_scaled,y_train)

pred_val = model.predict(X_val_scaled)
evulation_metric_val = evulation_metric(y_val, pred_val)
evulation_metric_val

0.6795058139534883

## 3. Cross-validation (data)

## 4. evulation metrics 확인

(6000, 2) (2000, 2) (2000, 2) (6000,) (2000,) (2000,)


In [ ]:
clf = SGDClassifier()
clf2 = LogisticRegression()
clf3 = DecisionTreeClassifier()
clf4 = RandomForestClassifier()

clf.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)
clf4.fit(X_train, y_train)

pred_train = clf.predict(X_train)
pred_train2 = clf2.predict(X_train)
pred_train3 = clf3.predict(X_train)
pred_train4 = clf4.predict(X_train)

pred_val = clf.predict(X_val)
pred_val2 = clf2.predict(X_val)
pred_val3 = clf3.predict(X_val)
pred_val4 = clf4.predict(X_val)

evulation_metric_train = evulation_metric(y_train, pred_train)
evulation_metric_val = evulation_metric(y_val, pred_val)

evulation_metric_train2 = evulation_metric(y_train, pred_train2)
evulation_metric_val2 = evulation_metric(y_val, pred_val2)

evulation_metric_train3 = evulation_metric(y_train, pred_train3)
evulation_metric_val3 = evulation_metric(y_val, pred_val3)

evulation_metric_train4 = evulation_metric(y_train, pred_train4)
evulation_metric_val4 = evulation_metric(y_val, pred_val4)

print(pred_val)
print(pred_val2)
print(pred_val3)
print(pred_val4)
print(y_val)

print("1. Linear Classifier, train/val = %.4f, %.4f" %(evulation_metric_train, evulation_metric_val))
print("2. Logistic Regression, train/val = %.4f, %.4f" %(evulation_metric_train2, evulation_metric_val2))
print("3. Decision Tree, train/val = %.4f, %.4f" %(evulation_metric_train3,evulation_metric_val3))
print("4. Random Forest, train/val = %.4f, %.4f" %(evulation_metric_train4, evulation_metric_val4))

[1 1 1 ... 1 1 1]
[1 1 1 ... 1 1 1]
[0 1 1 ... 0 1 0]
[0 1 1 ... 1 1 1]
3188    1
8293    1
1710    1
7510    1
1461    1
       ..
2834    0
449     1
6686    1
3561    1
9595    1
Name: target, Length: 2000, dtype: int64
1. Linear Classifier, train/val = 0.7651, 0.7651
2. Logistic Regression, train/val = 0.7652, 0.7651
3. Decision Tree, train/val = 1.0000, 0.6300
4. Random Forest, train/val = 1.0000, 0.6717


## 5. test 확인

In [ ]:
pred_test = clf.predict(X_test)
pred_test2 = clf2.predict(X_test)
pred_test3 = clf3.predict(X_test)
pred_test4 = clf4.predict(X_test)

evulation_metric_test = evulation_metric(y_test, pred_test2)
print(evulation_metric_test)

0.7661937075879087


## 6. 제출

In [ ]:
X_submission=test[['average_time_per_learning_session','average_login_time']]
print(X_submission)
preds=clf3.predict(X_submission)
preds

      average_time_per_learning_session  average_login_time
0                              7.047243           11.173051
1                             24.583327           13.448592
2                              1.707616           18.548201
3                             21.391389           13.383311
4                             18.126987           11.919663
...                                 ...                 ...
9995                          90.251023           11.924481
9996                          10.205804           12.395364
9997                          20.346781           17.036811
9998                         156.521711           15.758179
9999                          53.633453           19.618550

[10000 rows x 2 columns]


array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
submission = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/platform_subscribe/sample_submission.csv')
submission

user_id  target
0     0001d6e9       0
1     0002c77d       0
2     0002df5b       0
3     000b6068       0
4     00184a0c       0
...        ...     ...
9995  ffe2eba5       0
9996  ffe710f1       0
9997  ffeccdef       0
9998  fff3fcea       0
9999  fff4b04b       0

[10000 rows x 2 columns]

In [ ]:
submission['target']=preds
submission

user_id  target
0     0001d6e9       0
1     0002c77d       1
2     0002df5b       1
3     000b6068       1
4     00184a0c       0
...        ...     ...
9995  ffe2eba5       1
9996  ffe710f1       1
9997  ffeccdef       0
9998  fff3fcea       0
9999  fff4b04b       0

[10000 rows x 2 columns]

In [ ]:
submission.to_csv(base_path+"submission_1208_1.csv", index=False)