In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 데이터분석 4종 세트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

base_path = "/content/drive/MyDrive/Colab Notebooks/platform_subscribe/"

train = pd.read_csv(base_path + "train.csv")
test = pd.read_csv(base_path + "test.csv")
submission = pd.read_csv(base_path + "sample_submission.csv")

# 2. ML

In [ ]:
# 1. Linear Classifier
from sklearn.linear_model import SGDClassifier
# 2. Logistic Regression
from sklearn.linear_model import LogisticRegression
# 3. Decision Tree
from sklearn.tree import DecisionTreeClassifier
# 4. Random Forest
from sklearn.ensemble import RandomForestClassifier


# 평가 지표
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

evulation_metric = f1_score

# 3. overfitting 해결

## 1. feature 개수 줄이기



In [ ]:
X=train[['average_time_per_learning_session','average_login_time']]
y=train.target
X

average_time_per_learning_session  average_login_time
0                              8.427187           14.946163
1                             72.646087           18.453224
2                             21.774492           16.195228
3                             42.659066           17.628656
4                             30.744287           21.390656
...                                 ...                 ...
9995                          84.053558           14.727623
9996                          45.464833           19.374054
9997                         127.302411           18.240978
9998                           5.297234           18.783800
9999                          28.120031           13.073230

[10000 rows x 2 columns]

In [ ]:
from sklearn.model_selection import train_test_split
# 트테트테
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train,y_train, test_size=0.25, random_state=42)

# 6:2:2 = train: validation:test
print(X_train.shape, X_val.shape, X_test.shape, y_train.shape, y_val.shape, y_test.shape)

(6000, 2) (2000, 2) (2000, 2) (6000,) (2000,) (2000,)


In [ ]:
clf = SGDClassifier()
clf2 = LogisticRegression()
clf3 = DecisionTreeClassifier()
clf4 = RandomForestClassifier()

clf.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)
clf4.fit(X_train, y_train)

pred_train = clf.predict(X_train)
pred_train2 = clf2.predict(X_train)
pred_train3 = clf3.predict(X_train)
pred_train4 = clf4.predict(X_train)

pred_val = clf.predict(X_val)
pred_val2 = clf2.predict(X_val)
pred_val3 = clf3.predict(X_val)
pred_val4 = clf4.predict(X_val)

evulation_metric_train = evulation_metric(y_train, pred_train)
evulation_metric_val = evulation_metric(y_val, pred_val)

evulation_metric_train2 = evulation_metric(y_train, pred_train2)
evulation_metric_val2 = evulation_metric(y_val, pred_val2)

evulation_metric_train3 = evulation_metric(y_train, pred_train3)
evulation_metric_val3 = evulation_metric(y_val, pred_val3)

evulation_metric_train4 = evulation_metric(y_train, pred_train4)
evulation_metric_val4 = evulation_metric(y_val, pred_val4)

print(pred_val)
print(pred_val2)
print(pred_val3)
print(pred_val4)
print(y_val)

print("1. Linear Classifier, train/val = %.4f, %.4f" %(evulation_metric_train, evulation_metric_val))
print("2. Logistic Regression, train/val = %.4f, %.4f" %(evulation_metric_train2, evulation_metric_val2))
print("3. Decision Tree, train/val = %.4f, %.4f" %(evulation_metric_train3,evulation_metric_val3))
print("4. Random Forest, train/val = %.4f, %.4f" %(evulation_metric_train4, evulation_metric_val4))

[0 0 1 ... 1 0 1]
[1 1 1 ... 1 1 1]
[0 1 1 ... 0 1 1]
[0 1 1 ... 1 1 1]
3188    1
8293    1
1710    1
7510    1
1461    1
       ..
2834    0
449     1
6686    1
3561    1
9595    1
Name: target, Length: 2000, dtype: int64
1. Linear Classifier, train/val = 0.7195, 0.7069
2. Logistic Regression, train/val = 0.7652, 0.7651
3. Decision Tree, train/val = 1.0000, 0.6279
4. Random Forest, train/val = 1.0000, 0.6744


## 5. test 확인

In [ ]:
pred_test = clf.predict(X_test)
pred_test2 = clf2.predict(X_test)
pred_test3 = clf3.predict(X_test)
pred_test4 = clf4.predict(X_test)

evulation_metric_test = evulation_metric(y_test, pred_test3)
print(evulation_metric_test)

0.6248995983935743


## 6. 제출

In [ ]:
X_submission=test[['average_time_per_learning_session','average_login_time']]
print(X_submission)
preds=clf3.predict(X_submission)
preds

      average_time_per_learning_session  average_login_time
0                              7.047243           11.173051
1                             24.583327           13.448592
2                              1.707616           18.548201
3                             21.391389           13.383311
4                             18.126987           11.919663
...                                 ...                 ...
9995                          90.251023           11.924481
9996                          10.205804           12.395364
9997                          20.346781           17.036811
9998                         156.521711           15.758179
9999                          53.633453           19.618550

[10000 rows x 2 columns]


array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
submission = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/platform_subscribe/sample_submission.csv')
submission

user_id  target
0     0001d6e9       0
1     0002c77d       0
2     0002df5b       0
3     000b6068       0
4     00184a0c       0
...        ...     ...
9995  ffe2eba5       0
9996  ffe710f1       0
9997  ffeccdef       0
9998  fff3fcea       0
9999  fff4b04b       0

[10000 rows x 2 columns]

In [ ]:
submission['target']=preds
submission

user_id  target
0     0001d6e9       0
1     0002c77d       1
2     0002df5b       1
3     000b6068       1
4     00184a0c       0
...        ...     ...
9995  ffe2eba5       1
9996  ffe710f1       1
9997  ffeccdef       0
9998  fff3fcea       0
9999  fff4b04b       0

[10000 rows x 2 columns]

In [ ]:
submission.to_csv(base_path+"submission_1208_3.csv", index=False)